/*
 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0 - 2021-10-23
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.uqam.tool.vivoproxy.swagger.client.api;

import ca.uqam.tool.vivoproxy.swagger.client.handler.ApiException;
import ca.uqam.tool.vivoproxy.swagger.client.model.ModelApiResponse;
import ca.uqam.tool.vivoproxy.swagger.client.model.VivoProperties;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminApi
 */
@Ignore
public class AdminApiTest {

    private final AdminApi api = new AdminApi();

    /**
     * Get remote VIVO properties
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVivoPropertiesTest() throws ApiException {
        VivoProperties response = api.getVivoProperties();

        // TODO: test validations
    }
    /**
     * Ping VIVO instance
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pingVivoTest() throws ApiException {
        ModelApiResponse response = api.pingVivo();

        // TODO: test validations
    }
    /**
     * Send reindex SOLR index signal to VIVO instance
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void reindexVIVOTest() throws ApiException {
        ModelApiResponse response = api.reindexVIVO();

        // TODO: test validations
    }
    /**
     * Set remote VIVO properties
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setVivoPropertiesTest() throws ApiException {
        VivoProperties body = null;
        VivoProperties response = api.setVivoProperties(body);

        // TODO: test validations
    }
}
