/*
 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0 - 2021-10-23
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.uqam.tool.vivoproxy.swagger.client.api;

import ca.uqam.tool.vivoproxy.swagger.client.handler.ApiException;
import ca.uqam.tool.vivoproxy.swagger.client.model.AuthorOfADocument;
import ca.uqam.tool.vivoproxy.swagger.client.model.Document;
import ca.uqam.tool.vivoproxy.swagger.client.model.ModelApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentApi
 */
@Ignore
public class DocumentApiTest {

    private final DocumentApi api = new DocumentApi();

    /**
     * Create a document in VIVO
     *
     * This can only be done by the logged in person.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDocumentTest() throws ApiException {
        Document body = null;
        ModelApiResponse response = api.createDocument(body);

        // TODO: test validations
    }
    /**
     * Associate a document to an Author
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void documentAddAuthorForTest() throws ApiException {
        AuthorOfADocument body = null;
        ModelApiResponse response = api.documentAddAuthorFor(body);

        // TODO: test validations
    }
}
