/*
 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0 - 2021-10-23
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.uqam.tool.vivoproxy.swagger.client.api;

import ca.uqam.tool.vivoproxy.swagger.client.handler.ApiException;
import ca.uqam.tool.vivoproxy.swagger.client.model.Image;
import ca.uqam.tool.vivoproxy.swagger.client.model.IndividualType;
import ca.uqam.tool.vivoproxy.swagger.client.model.LinguisticLabel;
import ca.uqam.tool.vivoproxy.swagger.client.model.ModelAPIResponse;
import ca.uqam.tool.vivoproxy.swagger.client.model.Statement;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IndividualApi
 */
@Ignore
public class IndividualApiTest {

    private final IndividualApi api = new IndividualApi();

    /**
     * Get an individual by IRI
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIndvByIRITest() throws ApiException {
        String IRI = null;
        String response = api.getIndvByIRI(IRI);

        // TODO: test validations
    }
    /**
     * Get an individual IRI by label (rdfs:label)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIndvByLabelTest() throws ApiException {
        String label = null;
        String response = api.getIndvByLabel(label);

        // TODO: test validations
    }
    /**
     * Associate an image to an individual
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indvAddImageTest() throws ApiException {
        Image body = null;
        ModelAPIResponse response = api.indvAddImage(body);

        // TODO: test validations
    }
    /**
     * Add a label to an individual
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indvAddLabelTest() throws ApiException {
        String IRI = null;
        List<LinguisticLabel> body = null;
        ModelAPIResponse response = api.indvAddLabel(IRI, body);

        // TODO: test validations
    }
    /**
     * Adding statement
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indvAddStatementTest() throws ApiException {
        Statement body = null;
        ModelAPIResponse response = api.indvAddStatement(body);

        // TODO: test validations
    }
    /**
     * Associate a type to an individual
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indvAddTypeTest() throws ApiException {
        IndividualType body = null;
        ModelAPIResponse response = api.indvAddType(body);

        // TODO: test validations
    }
}
