/*
 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.uqam.tool.vivoproxy.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PersonMemberOf
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-06-17T09:02:12.122-04:00")
public class PersonMemberOf {
  @SerializedName("personIRI")
  private String personIRI = null;

  @SerializedName("organisationIRI")
  private String organisationIRI = null;

  @SerializedName("organisationName")
  private String organisationName = null;

  @SerializedName("roleLabel")
  private String roleLabel = null;

  @SerializedName("vivoPositionIRI")
  private String vivoPositionIRI = null;

  @SerializedName("vivoOrganisationTypeIRI")
  private String vivoOrganisationTypeIRI = null;

  @SerializedName("startField_year")
  private String startFieldYear = null;

  @SerializedName("endField_year")
  private String endFieldYear = null;

  public PersonMemberOf personIRI(String personIRI) {
    this.personIRI = personIRI;
    return this;
  }

   /**
   * Get personIRI
   * @return personIRI
  **/
  @ApiModelProperty(example = "http://localhost:8080/vivo/individual/n733", value = "")
  public String getPersonIRI() {
    return personIRI;
  }

  public void setPersonIRI(String personIRI) {
    this.personIRI = personIRI;
  }

  public PersonMemberOf organisationIRI(String organisationIRI) {
    this.organisationIRI = organisationIRI;
    return this;
  }

   /**
   * Get organisationIRI
   * @return organisationIRI
  **/
  @ApiModelProperty(example = "http://localhost:8080/vivo/individual/n4762", value = "")
  public String getOrganisationIRI() {
    return organisationIRI;
  }

  public void setOrganisationIRI(String organisationIRI) {
    this.organisationIRI = organisationIRI;
  }

  public PersonMemberOf organisationName(String organisationName) {
    this.organisationName = organisationName;
    return this;
  }

   /**
   * Get organisationName
   * @return organisationName
  **/
  @ApiModelProperty(example = "Harvard University", value = "")
  public String getOrganisationName() {
    return organisationName;
  }

  public void setOrganisationName(String organisationName) {
    this.organisationName = organisationName;
  }

  public PersonMemberOf roleLabel(String roleLabel) {
    this.roleLabel = roleLabel;
    return this;
  }

   /**
   * Get roleLabel
   * @return roleLabel
  **/
  @ApiModelProperty(example = "Professor", value = "")
  public String getRoleLabel() {
    return roleLabel;
  }

  public void setRoleLabel(String roleLabel) {
    this.roleLabel = roleLabel;
  }

  public PersonMemberOf vivoPositionIRI(String vivoPositionIRI) {
    this.vivoPositionIRI = vivoPositionIRI;
    return this;
  }

   /**
   * Get vivoPositionIRI
   * @return vivoPositionIRI
  **/
  @ApiModelProperty(example = "http://vivoweb.org/ontology/core#FacultyPosition", value = "")
  public String getVivoPositionIRI() {
    return vivoPositionIRI;
  }

  public void setVivoPositionIRI(String vivoPositionIRI) {
    this.vivoPositionIRI = vivoPositionIRI;
  }

  public PersonMemberOf vivoOrganisationTypeIRI(String vivoOrganisationTypeIRI) {
    this.vivoOrganisationTypeIRI = vivoOrganisationTypeIRI;
    return this;
  }

   /**
   * Get vivoOrganisationTypeIRI
   * @return vivoOrganisationTypeIRI
  **/
  @ApiModelProperty(example = "http://vivoweb.org/ontology/core#University", value = "")
  public String getVivoOrganisationTypeIRI() {
    return vivoOrganisationTypeIRI;
  }

  public void setVivoOrganisationTypeIRI(String vivoOrganisationTypeIRI) {
    this.vivoOrganisationTypeIRI = vivoOrganisationTypeIRI;
  }

  public PersonMemberOf startFieldYear(String startFieldYear) {
    this.startFieldYear = startFieldYear;
    return this;
  }

   /**
   * Get startFieldYear
   * @return startFieldYear
  **/
  @ApiModelProperty(value = "")
  public String getStartFieldYear() {
    return startFieldYear;
  }

  public void setStartFieldYear(String startFieldYear) {
    this.startFieldYear = startFieldYear;
  }

  public PersonMemberOf endFieldYear(String endFieldYear) {
    this.endFieldYear = endFieldYear;
    return this;
  }

   /**
   * Get endFieldYear
   * @return endFieldYear
  **/
  @ApiModelProperty(value = "")
  public String getEndFieldYear() {
    return endFieldYear;
  }

  public void setEndFieldYear(String endFieldYear) {
    this.endFieldYear = endFieldYear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonMemberOf personMemberOf = (PersonMemberOf) o;
    return Objects.equals(this.personIRI, personMemberOf.personIRI) &&
        Objects.equals(this.organisationIRI, personMemberOf.organisationIRI) &&
        Objects.equals(this.organisationName, personMemberOf.organisationName) &&
        Objects.equals(this.roleLabel, personMemberOf.roleLabel) &&
        Objects.equals(this.vivoPositionIRI, personMemberOf.vivoPositionIRI) &&
        Objects.equals(this.vivoOrganisationTypeIRI, personMemberOf.vivoOrganisationTypeIRI) &&
        Objects.equals(this.startFieldYear, personMemberOf.startFieldYear) &&
        Objects.equals(this.endFieldYear, personMemberOf.endFieldYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personIRI, organisationIRI, organisationName, roleLabel, vivoPositionIRI, vivoOrganisationTypeIRI, startFieldYear, endFieldYear);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonMemberOf {\n");
    
    sb.append("    personIRI: ").append(toIndentedString(personIRI)).append("\n");
    sb.append("    organisationIRI: ").append(toIndentedString(organisationIRI)).append("\n");
    sb.append("    organisationName: ").append(toIndentedString(organisationName)).append("\n");
    sb.append("    roleLabel: ").append(toIndentedString(roleLabel)).append("\n");
    sb.append("    vivoPositionIRI: ").append(toIndentedString(vivoPositionIRI)).append("\n");
    sb.append("    vivoOrganisationTypeIRI: ").append(toIndentedString(vivoOrganisationTypeIRI)).append("\n");
    sb.append("    startFieldYear: ").append(toIndentedString(startFieldYear)).append("\n");
    sb.append("    endFieldYear: ").append(toIndentedString(endFieldYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

