/*
 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0 - 2021-10-23
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.uqam.tool.vivoproxy.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AuthorOfADocument
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-16T08:26:24.631-05:00[America/New_York]")
public class AuthorOfADocument {
  @SerializedName("documentIRI")
  private String documentIRI = null;

  @SerializedName("personIRI")
  private String personIRI = null;

  public AuthorOfADocument documentIRI(String documentIRI) {
    this.documentIRI = documentIRI;
    return this;
  }

   /**
   * Get documentIRI
   * @return documentIRI
  **/
  @Schema(example = "http://localhost:8080/vivo/individual/n7440", required = true, description = "")
  public String getDocumentIRI() {
    return documentIRI;
  }

  public void setDocumentIRI(String documentIRI) {
    this.documentIRI = documentIRI;
  }

  public AuthorOfADocument personIRI(String personIRI) {
    this.personIRI = personIRI;
    return this;
  }

   /**
   * Get personIRI
   * @return personIRI
  **/
  @Schema(example = "http://localhost:8080/vivo/individual/n32", required = true, description = "")
  public String getPersonIRI() {
    return personIRI;
  }

  public void setPersonIRI(String personIRI) {
    this.personIRI = personIRI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorOfADocument authorOfADocument = (AuthorOfADocument) o;
    return Objects.equals(this.documentIRI, authorOfADocument.documentIRI) &&
        Objects.equals(this.personIRI, authorOfADocument.personIRI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentIRI, personIRI);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorOfADocument {\n");
    
    sb.append("    documentIRI: ").append(toIndentedString(documentIRI)).append("\n");
    sb.append("    personIRI: ").append(toIndentedString(personIRI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
