/*
 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.uqam.tool.vivoproxy.swagger.client.api;

import ca.uqam.tool.vivoproxy.swagger.client.handler.ApiException;
import ca.uqam.tool.vivoproxy.swagger.client.model.Vivo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VivoApi
 */
@Ignore
public class VivoApiTest {

    private final VivoApi api = new VivoApi();

    
    /**
     * Get an individual by IRI
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getindividualByIRITest() throws ApiException {
        String IRI = null;
        Vivo response = api.getindividualByIRI(IRI);

        // TODO: test validations
    }
    
}
