package ca.uqam.tool.vivoproxy.swagger.server.api;



import java.io.IOException;

import javax.ws.rs.core.Response;

import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

import ca.uqam.tool.vivoproxy.swagger.api.ApiException;
import ca.uqam.tool.vivoproxy.swagger.api.NotFoundException;
import ca.uqam.tool.vivoproxy.swagger.api.OrganizationApi;
import ca.uqam.vocab.proxy.model.Organization;
import ca.uqam.tool.vivoproxy.swagger.server.api.sample.SampleValues;

/*

 * VIVO Proxy API
 * Proxy API for VIVO Data Manipulation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * API tests for OrganizationApi
 */
public class OrganizationApiTest {

    private final OrganizationApi api = new OrganizationApi(null);
    public static void main(String[]  args) throws IOException, OWLOntologyCreationException, OWLOntologyStorageException, ApiException {
        OrganizationApiTest apiTest = new OrganizationApiTest();
        if (true) apiTest.createOrganizationTest();
        
        System.out.println("Done!");

    }

    
    /**
     * Create an organization in VIVO 
     *
     * This can only be done by the logged in VIVO.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    public void createOrganizationTest() throws ApiException {
        Organization body = new Organization();
        body.setName(SampleValues.LABEL_UNIVERSITE_DU_QUEBEC_A_MONTREAL);
        body.setOrganizationType(SampleValues.IRI_VIVO_UNIVERSITY);
        Response result = api.createOrganization(body, null);
        System.out.println(result);
    }
    
}
